//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceSnap.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoiceSnap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppName => ResourceManager.GetString("AppName", resourceCulture) ?? "";
        public static string AppSlogan => ResourceManager.GetString("AppSlogan", resourceCulture) ?? "";
        public static string NavGeneral => ResourceManager.GetString("NavGeneral", resourceCulture) ?? "";
        public static string NavHotkeys => ResourceManager.GetString("NavHotkeys", resourceCulture) ?? "";
        public static string NavAbout => ResourceManager.GetString("NavAbout", resourceCulture) ?? "";
        public static string PageTitleGeneral => ResourceManager.GetString("PageTitleGeneral", resourceCulture) ?? "";
        public static string SectionBehavior => ResourceManager.GetString("SectionBehavior", resourceCulture) ?? "";
        public static string AutoHideIndicator => ResourceManager.GetString("AutoHideIndicator", resourceCulture) ?? "";
        public static string StartWithSystem => ResourceManager.GetString("StartWithSystem", resourceCulture) ?? "";
        public static string SectionAudio => ResourceManager.GetString("SectionAudio", resourceCulture) ?? "";
        public static string DetectingDevice => ResourceManager.GetString("DetectingDevice", resourceCulture) ?? "";
        public static string PageTitleHotkeys => ResourceManager.GetString("PageTitleHotkeys", resourceCulture) ?? "";
        public static string SectionRecordControl => ResourceManager.GetString("SectionRecordControl", resourceCulture) ?? "";
        public static string LongPressTrigger => ResourceManager.GetString("LongPressTrigger", resourceCulture) ?? "";
        public static string ChangeHotkey => ResourceManager.GetString("ChangeHotkey", resourceCulture) ?? "";
        public static string HotkeyHint => ResourceManager.GetString("HotkeyHint", resourceCulture) ?? "";
        public static string VersionPrefix => ResourceManager.GetString("VersionPrefix", resourceCulture) ?? "";
        public static string AboutDescription => ResourceManager.GetString("AboutDescription", resourceCulture) ?? "";
        public static string AboutAuthor => ResourceManager.GetString("AboutAuthor", resourceCulture) ?? "";
        public static string RunningMode => ResourceManager.GetString("RunningMode", resourceCulture) ?? "";
        public static string Detecting => ResourceManager.GetString("Detecting", resourceCulture) ?? "";
        public static string VisitWebsite => ResourceManager.GetString("VisitWebsite", resourceCulture) ?? "";
        public static string CheckUpdate => ResourceManager.GetString("CheckUpdate", resourceCulture) ?? "";
        public static string StatusReady => ResourceManager.GetString("StatusReady", resourceCulture) ?? "";
        public static string StatusRecording => ResourceManager.GetString("StatusRecording", resourceCulture) ?? "";
        public static string StatusRecognizing => ResourceManager.GetString("StatusRecognizing", resourceCulture) ?? "";
        public static string StatusCancelled => ResourceManager.GetString("StatusCancelled", resourceCulture) ?? "";
        public static string StatusNoVoice => ResourceManager.GetString("StatusNoVoice", resourceCulture) ?? "";
        public static string StatusInputDone => ResourceManager.GetString("StatusInputDone", resourceCulture) ?? "";
        public static string StatusEngineNotReady => ResourceManager.GetString("StatusEngineNotReady", resourceCulture) ?? "";
        public static string StatusClipboardBusy => ResourceManager.GetString("StatusClipboardBusy", resourceCulture) ?? "";
        public static string StatusError => ResourceManager.GetString("StatusError", resourceCulture) ?? "";
        public static string StatusLoading => ResourceManager.GetString("StatusLoading", resourceCulture) ?? "";
        public static string StatusNoContent => ResourceManager.GetString("StatusNoContent", resourceCulture) ?? "";
        public static string StatusInitializing => ResourceManager.GetString("StatusInitializing", resourceCulture) ?? "";
        public static string DownloadingUpdate => ResourceManager.GetString("DownloadingUpdate", resourceCulture) ?? "";
        public static string ApplyingUpdate => ResourceManager.GetString("ApplyingUpdate", resourceCulture) ?? "";
        public static string VersionInfoFailed => ResourceManager.GetString("VersionInfoFailed", resourceCulture) ?? "";
        public static string CheckUpdateFailed => ResourceManager.GetString("CheckUpdateFailed", resourceCulture) ?? "";
        public static string EngineFailed => ResourceManager.GetString("EngineFailed", resourceCulture) ?? "";
        public static string DownloadFailed => ResourceManager.GetString("DownloadFailed", resourceCulture) ?? "";
        public static string UpdateFailed => ResourceManager.GetString("UpdateFailed", resourceCulture) ?? "";
        public static string UpdateError => ResourceManager.GetString("UpdateError", resourceCulture) ?? "";
        public static string CannotGetPath => ResourceManager.GetString("CannotGetPath", resourceCulture) ?? "";
        public static string InvalidDownload => ResourceManager.GetString("InvalidDownload", resourceCulture) ?? "";
        public static string HotkeyUpdated => ResourceManager.GetString("HotkeyUpdated", resourceCulture) ?? "";
        public static string PressAnyKey => ResourceManager.GetString("PressAnyKey", resourceCulture) ?? "";
        public static string IsLatestVersion => ResourceManager.GetString("IsLatestVersion", resourceCulture) ?? "";
        public static string CheckingUpdate => ResourceManager.GetString("CheckingUpdate", resourceCulture) ?? "";
        public static string InputDevice => ResourceManager.GetString("InputDevice", resourceCulture) ?? "";
        public static string KeySpace => ResourceManager.GetString("KeySpace", resourceCulture) ?? "";
        public static string KeyEnter => ResourceManager.GetString("KeyEnter", resourceCulture) ?? "";
        public static string TrayShow => ResourceManager.GetString("TrayShow", resourceCulture) ?? "";
        public static string TrayExit => ResourceManager.GetString("TrayExit", resourceCulture) ?? "";
        public static string TrayTooltip => ResourceManager.GetString("TrayTooltip", resourceCulture) ?? "";
        public static string InitPreparing => ResourceManager.GetString("InitPreparing", resourceCulture) ?? "";
        public static string InitSyncModel => ResourceManager.GetString("InitSyncModel", resourceCulture) ?? "";
        public static string InitOptimizing => ResourceManager.GetString("InitOptimizing", resourceCulture) ?? "";
        public static string InitExtracting => ResourceManager.GetString("InitExtracting", resourceCulture) ?? "";
        public static string InitComplete => ResourceManager.GetString("InitComplete", resourceCulture) ?? "";
        public static string InitFailed => ResourceManager.GetString("InitFailed", resourceCulture) ?? "";
    }
}
